<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Elizabeth Brown - BioSite</title>
    <link rel="stylesheet" href="site.css">
</head>
<body>
    <header class="landing-page">
        <div class="container">
            <h1>Welcome to Elizabeth's BioSite</h1>
            <p>Discover the story of Elizabeth</p>
            <nav>
                <ul>
                    <li><a href="C:\csd\bioSite\AboutPage.html">About</a></li>
                    <li><a href="C:\csd\bioSite\HobbiesPage.html">Hobbies</a></li>
                    <li><a href="C:\csd\bioSite\GoalsPage.html">Goals</a></li>
                </ul>
            </nav>
        </div>
    </header>
</body>
</html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Elizabeth - BioSite</title>
    <link rel="stylesheet" href="site.css">
</head>
<body>
    <nav>
        <ul>
           <li><a href="C:\csd\bioSite\AboutPage.html">About</a></li>
           <li><a href="C:\csd\bioSite\HobbiesPage.html">Hobbies</a></li>
           <li><a href="C:\csd\bioSite\GoalsPage.html">Goals</a></li>

        </ul>
    </nav>
    <section class="about-page">
        <div class="container">
            <h2>About Elizabeth</h2>
            <p>Elizabeth feels quite at home in North Carolina, which is where she spent most of her childhood and started her trajectory towards becoming a nurse. A fiercely loyal mom of four boys, Elizabeth has dedicated her life to both being a mother and amazing wife. When she isn’t having fun with her family she is a Nursing Manager. She got into healthcare motivated by a desire to help people. She leads her team with a combination of humility and expertise while embodying a wonderful person that is driven by helping others.
Elizabeth enjoys spending time with her family when she is not working. She enjoys lounging out on the beach, playing around with new recipes in the kitchen, or just enjoying each other's presence. These moments are what make her genuinely happy. Elizabeth, an excellent home cook and baker who pretty much always brings the best desserts to gatherings.
Looking to the future, Elizabeth sees herself in an educator role, excited at the opportunity of sharing what she knows with a new generation of nurses. She thrives on making sure the people in her circle are filled with the knowledge she possesses. She has a unique dedication to making sure that everyone and everything is taken care of in the way it should be. She is an amazing mother and even more amazing wife. Her dedication and love for her friends and family will continue to flourish for the rest of her career and life.</p>
            <div class="gallery">
                <img src="image1.jpg" alt="Elizabeth Image 1">
                <img src="image2.jpg" alt="Elizabeth Image 2">
                <img src="image3.jpg" alt="Elizabeth Image 3">
            </div>
        </div>
    </section>
<a href="C:\csd\bioSite\index.html">
    <button type="button">Back to HOME</button>
</a>

</body>
</html>

body {
    font-family: Arial, sans-serif;
    line-height: 1.6;
    margin: 0;
    padding: 0;
    background-color: #f4f4f4;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Elizabeth's Hobbies - BioSite</title>
    <link rel="stylesheet" href="site.css">
</head>
<body>
    <nav>
        <ul>
            <li><a href="C:\csd\bioSite\AboutPage.html">About</a></li>
            <li><a href="C:\csd\bioSite\HobbiesPage.html">Hobbies</a></li>
            <li><a href="C:\csd\bioSite\GoalsPage.html">Goals</a></li>

        </ul>
    </nav>
    <section class="hobbies-page">
        <div class="container">
            <h2>Elizabeth's Hobbies</h2>
            <p>Her hobbies include cooking, going to the beach, and spending quality time with her amazing family.</p>
            <div class="gallery">
                <img src="image4.jpg" alt="Hobby Image 1">
                <img src="image5.jpg" alt="Hobby Image 2">
                <img src="image6.jpg" alt="Hobby Image 3">
            </div>
        </div>
    </section>
<a href="C:\csd\bioSite\index.html">
    <button type="button">Back to HOME</button>
</a>

</body>
</html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Elizabeth's Goals - BioSite</title>
    <link rel="stylesheet" href="site.css">
</head>
<body>
    <nav>
        <ul>
            <li><a href="C:\csd\bioSite\AboutPage.html">About</a></li>
            <li><a href="C:\csd\bioSite\HobbiesPage.html">Hobbies</a></li>
            <li><a href="C:\csd\bioSite\GoalsPage.html">Goals</a></li>

        </ul>
    </nav>
    <footer class="goals-page">
        <div class="container">
            <h2>Elizabeth's Goals</h2>
            <p>Elizabeth's goals are to become an educator in the nursing field, retire, and travel the world.</p>
        </div>
    </footer>
<a href="C:\csd\bioSite\index.html">
    <button type="button">Back to HOME</button>
</a>

</body>
</html>

.container {
    width: 80%;
    margin: auto;
    overflow: hidden;
}

header.landing-page {
    background: #333;
    color: #fff;
    padding: 60px 0;
    text-align: center;
}

header.landing-page h1 {
    margin: 0;
    font-size: 2.5rem;
}

header.landing-page p {
    margin: 10px 0;
    font-size: 1.2rem;
}

header.landing-page nav ul {
    padding: 0;
    list-style: none;
}

header.landing-page nav ul li {
    display: inline;
    margin: 0 10px;
}

header.landing-page nav ul li a {
    color: #fff;
    text-decoration: none;
    font-weight: bold;
}

.about-page, .hobbies-page {
    background: #fff;
    padding: 40px 0;
    text-align: center;
}

.about-page h2, .hobbies-page h2 {
    color: #333;
    font-size: 2rem;
    margin-bottom: 20px;
}

.gallery {
    display: flex;
    justify-content: space-around;
    flex-wrap: wrap;
    margin-top: 20px;
}

.gallery img {
    width: 30%;
    margin-bottom: 20px;
    border-radius: 5px;
}

footer.contact-page {
    background: #333;
    color: #fff;
    padding: 20px 0;
    text-align: center;
}

footer.contact-page h2 {
    font-size: 1.5rem;
    margin-bottom: 10px;
}

footer.contact-page a {
    color: #ffcc00;
    text-decoration: none;
    font-weight: bold;
}

footer.contact-page a:hover {
    text-decoration: underline;
}

